# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'default_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1278, 395)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_copy_file = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_copy_file.setFont(font)
        self.groupBox_copy_file.setObjectName("groupBox_copy_file")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_copy_file)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_default = QtWidgets.QFrame(self.groupBox_copy_file)
        self.frame_default.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_default.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_default.setObjectName("frame_default")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_default)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_cancel = QtWidgets.QPushButton(self.frame_default)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout_4.addWidget(self.pushButton_cancel, 1, 0, 1, 1)
        self.gridLayout_copy_file = QtWidgets.QGridLayout()
        self.gridLayout_copy_file.setObjectName("gridLayout_copy_file")
        self.gridLayout_4.addLayout(self.gridLayout_copy_file, 0, 0, 1, 2)
        self.pushButton_accept = QtWidgets.QPushButton(self.frame_default)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.gridLayout_4.addWidget(self.pushButton_accept, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_default, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_copy_file, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройки по умолчанию"))
        self.groupBox_copy_file.setTitle(_translate("Dialog", "Перенос файлов"))
        self.pushButton_cancel.setText(_translate("Dialog", "Отмена"))
        self.pushButton_accept.setText(_translate("Dialog", "Принять"))
