# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Button(QtWidgets.QLineEdit):

	def __init__(self, parent):
		super(Button, self).__init__(parent)

		self.setAcceptDrops(True)

	def dragEnterEvent(self, e):

		if e.mimeData().hasUrls():
			e.accept()
		else:
			super(Button, self).dragEnterEvent(e)

	def dragMoveEvent(self, e):

		super(Button, self).dragMoveEvent(e)

	def dropEvent(self, e):

		if e.mimeData().hasUrls():
			for url in e.mimeData().urls():
				self.setText(os.path.normcase(url.toLocalFile()))
				e.accept()
		else:
			super(Button, self).dropEvent(e)
import os
import os


class Button(QtWidgets.QLineEdit):

	def __init__(self, parent):
		super(Button, self).__init__(parent)

		self.setAcceptDrops(True)

	def dragEnterEvent(self, e):

		if e.mimeData().hasUrls():
			e.accept()
		else:
			super(Button, self).dragEnterEvent(e)

	def dragMoveEvent(self, e):

		super(Button, self).dragMoveEvent(e)

	def dropEvent(self, e):

		if e.mimeData().hasUrls():
			for url in e.mimeData().urls():
				self.setText(os.path.normcase(url.toLocalFile()))
				e.accept()
		else:
			super(Button, self).dropEvent(e)


class Button(QtWidgets.QLineEdit):

	def __init__(self, parent):
		super(Button, self).__init__(parent)

		self.setAcceptDrops(True)

	def dragEnterEvent(self, e):

		if e.mimeData().hasUrls():
			e.accept()
		else:
			super(Button, self).dragEnterEvent(e)

	def dragMoveEvent(self, e):

		super(Button, self).dragMoveEvent(e)

	def dropEvent(self, e):

		if e.mimeData().hasUrls():
			for url in e.mimeData().urls():
				self.setText(os.path.normcase(url.toLocalFile()))
				e.accept()
		else:
			super(Button, self).dropEvent(e)


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(695, 313)
        font = QtGui.QFont()
        font.setPointSize(10)
        mainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.form = QtWidgets.QWidget()
        self.form.setObjectName("form")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_form_file = QtWidgets.QPushButton(self.form)
        self.pushButton_form_file.setObjectName("pushButton_form_file")
        self.gridLayout_2.addWidget(self.pushButton_form_file, 2, 0, 1, 3)
        self.pushButton_open_check_material_dir = QtWidgets.QPushButton(self.form)
        self.pushButton_open_check_material_dir.setObjectName("pushButton_open_check_material_dir")
        self.gridLayout_2.addWidget(self.pushButton_open_check_material_dir, 1, 2, 1, 1)
        self.label_unformat_file = QtWidgets.QLabel(self.form)
        self.label_unformat_file.setObjectName("label_unformat_file")
        self.gridLayout_2.addWidget(self.label_unformat_file, 0, 0, 1, 1)
        self.lineEdit_path_file_unformat_file = Button(self.form)
        self.lineEdit_path_file_unformat_file.setObjectName("lineEdit_path_file_unformat_file")
        self.gridLayout_2.addWidget(self.lineEdit_path_file_unformat_file, 0, 1, 1, 1)
        self.lineEdit_path_dir_check_material = Button(self.form)
        self.lineEdit_path_dir_check_material.setObjectName("lineEdit_path_dir_check_material")
        self.gridLayout_2.addWidget(self.lineEdit_path_dir_check_material, 1, 1, 1, 1)
        self.pushButton_open_unformat_file = QtWidgets.QPushButton(self.form)
        self.pushButton_open_unformat_file.setObjectName("pushButton_open_unformat_file")
        self.gridLayout_2.addWidget(self.pushButton_open_unformat_file, 0, 2, 1, 1)
        self.label_dir_check_material = QtWidgets.QLabel(self.form)
        self.label_dir_check_material.setObjectName("label_dir_check_material")
        self.gridLayout_2.addWidget(self.label_dir_check_material, 1, 0, 1, 1)
        self.tabWidget.addTab(self.form, "")
        self.sorting = QtWidgets.QWidget()
        self.sorting.setObjectName("sorting")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.sorting)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_open_load_manufacture_file = QtWidgets.QPushButton(self.sorting)
        self.pushButton_open_load_manufacture_file.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open_load_manufacture_file.sizePolicy().hasHeightForWidth())
        self.pushButton_open_load_manufacture_file.setSizePolicy(sizePolicy)
        self.pushButton_open_load_manufacture_file.setObjectName("pushButton_open_load_manufacture_file")
        self.gridLayout_3.addWidget(self.pushButton_open_load_manufacture_file, 2, 2, 1, 1)
        self.lineEdit_path_dir_finish = Button(self.sorting)
        self.lineEdit_path_dir_finish.setObjectName("lineEdit_path_dir_finish")
        self.gridLayout_3.addWidget(self.lineEdit_path_dir_finish, 3, 1, 1, 1)
        self.lineEdit_name_gk = QtWidgets.QLineEdit(self.sorting)
        self.lineEdit_name_gk.setEnabled(False)
        self.lineEdit_name_gk.setObjectName("lineEdit_name_gk")
        self.gridLayout_3.addWidget(self.lineEdit_name_gk, 4, 1, 1, 2)
        self.pushButton_open_material_sp_dir = QtWidgets.QPushButton(self.sorting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open_material_sp_dir.sizePolicy().hasHeightForWidth())
        self.pushButton_open_material_sp_dir.setSizePolicy(sizePolicy)
        self.pushButton_open_material_sp_dir.setObjectName("pushButton_open_material_sp_dir")
        self.gridLayout_3.addWidget(self.pushButton_open_material_sp_dir, 0, 2, 1, 1)
        self.checkBox_name_set = QtWidgets.QCheckBox(self.sorting)
        self.checkBox_name_set.setObjectName("checkBox_name_set")
        self.gridLayout_3.addWidget(self.checkBox_name_set, 5, 0, 1, 1)
        self.radioButton_load_manufacture = QtWidgets.QRadioButton(self.sorting)
        self.radioButton_load_manufacture.setObjectName("radioButton_load_manufacture")
        self.gridLayout_3.addWidget(self.radioButton_load_manufacture, 2, 0, 1, 1)
        self.pushButton_open_load_asu_file = QtWidgets.QPushButton(self.sorting)
        self.pushButton_open_load_asu_file.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open_load_asu_file.sizePolicy().hasHeightForWidth())
        self.pushButton_open_load_asu_file.setSizePolicy(sizePolicy)
        self.pushButton_open_load_asu_file.setObjectName("pushButton_open_load_asu_file")
        self.gridLayout_3.addWidget(self.pushButton_open_load_asu_file, 1, 2, 1, 1)
        self.radioButton_load_asu = QtWidgets.QRadioButton(self.sorting)
        self.radioButton_load_asu.setObjectName("radioButton_load_asu")
        self.gridLayout_3.addWidget(self.radioButton_load_asu, 1, 0, 1, 1)
        self.lineEdit_path_load_asu_file = Button(self.sorting)
        self.lineEdit_path_load_asu_file.setEnabled(False)
        self.lineEdit_path_load_asu_file.setObjectName("lineEdit_path_load_asu_file")
        self.gridLayout_3.addWidget(self.lineEdit_path_load_asu_file, 1, 1, 1, 1)
        self.label_material_sp = QtWidgets.QLabel(self.sorting)
        self.label_material_sp.setObjectName("label_material_sp")
        self.gridLayout_3.addWidget(self.label_material_sp, 0, 0, 1, 1)
        self.lineEdit_name_set = QtWidgets.QLineEdit(self.sorting)
        self.lineEdit_name_set.setEnabled(False)
        self.lineEdit_name_set.setObjectName("lineEdit_name_set")
        self.gridLayout_3.addWidget(self.lineEdit_name_set, 5, 1, 1, 2)
        self.pushButton_open_path_finish_dir = QtWidgets.QPushButton(self.sorting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open_path_finish_dir.sizePolicy().hasHeightForWidth())
        self.pushButton_open_path_finish_dir.setSizePolicy(sizePolicy)
        self.pushButton_open_path_finish_dir.setObjectName("pushButton_open_path_finish_dir")
        self.gridLayout_3.addWidget(self.pushButton_open_path_finish_dir, 3, 2, 1, 1)
        self.lineEdit_path_file_manufacture = Button(self.sorting)
        self.lineEdit_path_file_manufacture.setEnabled(False)
        self.lineEdit_path_file_manufacture.setObjectName("lineEdit_path_file_manufacture")
        self.gridLayout_3.addWidget(self.lineEdit_path_file_manufacture, 2, 1, 1, 1)
        self.lineEdit_path_dir_material_sp = Button(self.sorting)
        self.lineEdit_path_dir_material_sp.setObjectName("lineEdit_path_dir_material_sp")
        self.gridLayout_3.addWidget(self.lineEdit_path_dir_material_sp, 0, 1, 1, 1)
        self.label_finish_folder = QtWidgets.QLabel(self.sorting)
        self.label_finish_folder.setObjectName("label_finish_folder")
        self.gridLayout_3.addWidget(self.label_finish_folder, 3, 0, 1, 1)
        self.checkBox_name_gk = QtWidgets.QCheckBox(self.sorting)
        self.checkBox_name_gk.setObjectName("checkBox_name_gk")
        self.gridLayout_3.addWidget(self.checkBox_name_gk, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_sorting_file_SP = QtWidgets.QPushButton(self.sorting)
        self.pushButton_sorting_file_SP.setObjectName("pushButton_sorting_file_SP")
        self.horizontalLayout.addWidget(self.pushButton_sorting_file_SP)
        self.pushButton_sorting_file_manufacture = QtWidgets.QPushButton(self.sorting)
        self.pushButton_sorting_file_manufacture.setObjectName("pushButton_sorting_file_manufacture")
        self.horizontalLayout.addWidget(self.pushButton_sorting_file_manufacture)
        self.gridLayout_3.addLayout(self.horizontalLayout, 7, 0, 1, 3)
        self.tabWidget.addTab(self.sorting, "")
        self.change = QtWidgets.QWidget()
        self.change.setObjectName("change")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.change)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_unloading_file = QtWidgets.QLabel(self.change)
        self.label_unloading_file.setObjectName("label_unloading_file")
        self.gridLayout_4.addWidget(self.label_unloading_file, 0, 0, 1, 1)
        self.pushButton_open_start_unloading_dir = QtWidgets.QPushButton(self.change)
        self.pushButton_open_start_unloading_dir.setObjectName("pushButton_open_start_unloading_dir")
        self.gridLayout_4.addWidget(self.pushButton_open_start_unloading_dir, 0, 2, 1, 1)
        self.pushButton_change_unloading_file = QtWidgets.QPushButton(self.change)
        self.pushButton_change_unloading_file.setObjectName("pushButton_change_unloading_file")
        self.gridLayout_4.addWidget(self.pushButton_change_unloading_file, 2, 0, 1, 3)
        self.lineEdit_path_dir_start_unloading_files = Button(self.change)
        self.lineEdit_path_dir_start_unloading_files.setObjectName("lineEdit_path_dir_start_unloading_files")
        self.gridLayout_4.addWidget(self.lineEdit_path_dir_start_unloading_files, 0, 1, 1, 1)
        self.label_path_dir_finish_unloading_files = QtWidgets.QLabel(self.change)
        self.label_path_dir_finish_unloading_files.setObjectName("label_path_dir_finish_unloading_files")
        self.gridLayout_4.addWidget(self.label_path_dir_finish_unloading_files, 1, 0, 1, 1)
        self.lineEdit_path_dir_finish_unloading_files = Button(self.change)
        self.lineEdit_path_dir_finish_unloading_files.setObjectName("lineEdit_path_dir_finish_unloading_files")
        self.gridLayout_4.addWidget(self.lineEdit_path_dir_finish_unloading_files, 1, 1, 1, 1)
        self.pushButton_open_finish_unloading_dir = QtWidgets.QPushButton(self.change)
        self.pushButton_open_finish_unloading_dir.setObjectName("pushButton_open_finish_unloading_dir")
        self.gridLayout_4.addWidget(self.pushButton_open_finish_unloading_dir, 1, 2, 1, 1)
        self.tabWidget.addTab(self.change, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 695, 23))
        self.menubar.setObjectName("menubar")
        self.menu_settings = QtWidgets.QMenu(self.menubar)
        self.menu_settings.setObjectName("menu_settings")
        self.menu_application = QtWidgets.QMenu(self.menubar)
        self.menu_application.setObjectName("menu_application")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.action_default_window = QtWidgets.QAction(mainWindow)
        self.action_default_window.setObjectName("action_default_window")
        self.action_form_file = QtWidgets.QAction(mainWindow)
        self.action_form_file.setCheckable(True)
        self.action_form_file.setChecked(False)
        self.action_form_file.setObjectName("action_form_file")
        self.action_sorting_file = QtWidgets.QAction(mainWindow)
        self.action_sorting_file.setCheckable(True)
        self.action_sorting_file.setChecked(False)
        self.action_sorting_file.setObjectName("action_sorting_file")
        self.action_change_unloading = QtWidgets.QAction(mainWindow)
        self.action_change_unloading.setCheckable(True)
        self.action_change_unloading.setChecked(False)
        self.action_change_unloading.setObjectName("action_change_unloading")
        self.menu_settings.addAction(self.action_default_window)
        self.menu_application.addAction(self.action_form_file)
        self.menu_application.addAction(self.action_sorting_file)
        self.menu_application.addAction(self.action_change_unloading)
        self.menubar.addAction(self.menu_settings.menuAction())
        self.menubar.addAction(self.menu_application.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.checkBox_name_gk.toggled['bool'].connect(self.lineEdit_name_gk.setEnabled) # type: ignore
        self.checkBox_name_set.toggled['bool'].connect(self.lineEdit_name_set.setEnabled) # type: ignore
        self.radioButton_load_asu.toggled['bool'].connect(self.lineEdit_path_load_asu_file.setEnabled) # type: ignore
        self.radioButton_load_asu.toggled['bool'].connect(self.pushButton_open_load_asu_file.setEnabled) # type: ignore
        self.radioButton_load_manufacture.toggled['bool'].connect(self.lineEdit_path_file_manufacture.setEnabled) # type: ignore
        self.radioButton_load_manufacture.toggled['bool'].connect(self.pushButton_open_load_manufacture_file.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Главное окно"))
        self.pushButton_form_file.setText(_translate("mainWindow", "Сформировать выгрузку из файла"))
        self.pushButton_open_check_material_dir.setText(_translate("mainWindow", "Открыть"))
        self.label_unformat_file.setText(_translate("mainWindow", "Неподготовленный файл"))
        self.pushButton_open_unformat_file.setText(_translate("mainWindow", "Открыть"))
        self.label_dir_check_material.setText(_translate("mainWindow", "Папка с материалами"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.form), _translate("mainWindow", "Формирование выгрузки"))
        self.pushButton_open_load_manufacture_file.setText(_translate("mainWindow", "Открыть"))
        self.pushButton_open_material_sp_dir.setText(_translate("mainWindow", "Открыть"))
        self.checkBox_name_set.setText(_translate("mainWindow", "Наименование к-та"))
        self.radioButton_load_manufacture.setText(_translate("mainWindow", "Файл выгрузки «.csv»"))
        self.pushButton_open_load_asu_file.setText(_translate("mainWindow", "Открыть"))
        self.radioButton_load_asu.setText(_translate("mainWindow", "Файл выгрузки «.xlsx»"))
        self.label_material_sp.setText(_translate("mainWindow", "Папка с материалами"))
        self.pushButton_open_path_finish_dir.setText(_translate("mainWindow", "Открыть"))
        self.label_finish_folder.setText(_translate("mainWindow", "Конечная папка"))
        self.checkBox_name_gk.setText(_translate("mainWindow", "Наименование ГК"))
        self.pushButton_sorting_file_SP.setText(_translate("mainWindow", "Преобразовать файлы СП"))
        self.pushButton_sorting_file_manufacture.setText(_translate("mainWindow", "Преобразовать файлы с производства"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sorting), _translate("mainWindow", "Сортировка файлов"))
        self.label_unloading_file.setText(_translate("mainWindow", "Исходные выгрузки"))
        self.pushButton_open_start_unloading_dir.setText(_translate("mainWindow", "Открыть"))
        self.pushButton_change_unloading_file.setText(_translate("mainWindow", "Изменить файл выгрузки"))
        self.label_path_dir_finish_unloading_files.setText(_translate("mainWindow", "Конечная папка"))
        self.pushButton_open_finish_unloading_dir.setText(_translate("mainWindow", "Открыть"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.change), _translate("mainWindow", "Изменение выгрузки"))
        self.menu_settings.setTitle(_translate("mainWindow", "Настройки"))
        self.menu_application.setTitle(_translate("mainWindow", "Доступные приложения"))
        self.action_default_window.setText(_translate("mainWindow", "Настройки по умолчанию"))
        self.action_form_file.setText(_translate("mainWindow", "Формирование выгрузки"))
        self.action_sorting_file.setText(_translate("mainWindow", "Сортировка файлов"))
        self.action_change_unloading.setText(_translate("mainWindow", "Изменение выгрузки"))
