# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Button(QtWidgets.QLineEdit):

	def __init__(self, parent):
		super(Button, self).__init__(parent)

		self.setAcceptDrops(True)

	def dragEnterEvent(self, e):

		if e.mimeData().hasUrls():
			e.accept()
		else:
			super(Button, self).dragEnterEvent(e)

	def dragMoveEvent(self, e):

		super(Button, self).dragMoveEvent(e)

	def dropEvent(self, e):

		if e.mimeData().hasUrls():
			for url in e.mimeData().urls():
				self.setText(os.path.normcase(url.toLocalFile()))
				e.accept()
		else:
			super(Button, self).dropEvent(e)


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(692, 353)
        font = QtGui.QFont()
        font.setPointSize(10)
        mainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_finish_folder = QtWidgets.QLabel(self.centralwidget)
        self.label_finish_folder.setObjectName("label_finish_folder")
        self.gridLayout.addWidget(self.label_finish_folder, 8, 0, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout.addWidget(self.pushButton_start, 11, 0, 1, 4)
        self.pushButton_open_path_finish_dir = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open_path_finish_dir.sizePolicy().hasHeightForWidth())
        self.pushButton_open_path_finish_dir.setSizePolicy(sizePolicy)
        self.pushButton_open_path_finish_dir.setObjectName("pushButton_open_path_finish_dir")
        self.gridLayout.addWidget(self.pushButton_open_path_finish_dir, 8, 3, 1, 1)
        self.pushButton_open_unformat_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_unformat_file.setObjectName("pushButton_open_unformat_file")
        self.gridLayout.addWidget(self.pushButton_open_unformat_file, 0, 3, 1, 1)
        self.lineEdit_name_gk = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name_gk.setEnabled(False)
        self.lineEdit_name_gk.setObjectName("lineEdit_name_gk")
        self.gridLayout.addWidget(self.lineEdit_name_gk, 9, 1, 1, 3)
        self.checkBox_name_gk = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_name_gk.setObjectName("checkBox_name_gk")
        self.gridLayout.addWidget(self.checkBox_name_gk, 9, 0, 1, 1)
        self.lineEdit_path_file_manufacture = Button(self.centralwidget)
        self.lineEdit_path_file_manufacture.setEnabled(False)
        self.lineEdit_path_file_manufacture.setObjectName("lineEdit_path_file_manufacture")
        self.gridLayout.addWidget(self.lineEdit_path_file_manufacture, 7, 1, 1, 2)
        self.pushButton_open_load_manufacture_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_load_manufacture_file.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open_load_manufacture_file.sizePolicy().hasHeightForWidth())
        self.pushButton_open_load_manufacture_file.setSizePolicy(sizePolicy)
        self.pushButton_open_load_manufacture_file.setObjectName("pushButton_open_load_manufacture_file")
        self.gridLayout.addWidget(self.pushButton_open_load_manufacture_file, 7, 3, 1, 1)
        self.lineEdit_path_file_unformat_file = Button(self.centralwidget)
        self.lineEdit_path_file_unformat_file.setObjectName("lineEdit_path_file_unformat_file")
        self.gridLayout.addWidget(self.lineEdit_path_file_unformat_file, 0, 1, 1, 1)
        self.radioButton_load_manufacture = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_load_manufacture.setObjectName("radioButton_load_manufacture")
        self.gridLayout.addWidget(self.radioButton_load_manufacture, 7, 0, 1, 1)
        self.label_unloading_file = QtWidgets.QLabel(self.centralwidget)
        self.label_unloading_file.setObjectName("label_unloading_file")
        self.gridLayout.addWidget(self.label_unloading_file, 4, 0, 1, 1)
        self.radioButton_load_asu = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_load_asu.setObjectName("radioButton_load_asu")
        self.gridLayout.addWidget(self.radioButton_load_asu, 6, 0, 1, 1)
        self.label_material_sp = QtWidgets.QLabel(self.centralwidget)
        self.label_material_sp.setObjectName("label_material_sp")
        self.gridLayout.addWidget(self.label_material_sp, 3, 0, 1, 1)
        self.checkBox_name_set = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_name_set.setObjectName("checkBox_name_set")
        self.gridLayout.addWidget(self.checkBox_name_set, 10, 0, 1, 1)
        self.pushButton_form_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_form_file.setObjectName("pushButton_form_file")
        self.gridLayout.addWidget(self.pushButton_form_file, 1, 0, 1, 4)
        self.pushButton_open_material_sp_dir = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open_material_sp_dir.sizePolicy().hasHeightForWidth())
        self.pushButton_open_material_sp_dir.setSizePolicy(sizePolicy)
        self.pushButton_open_material_sp_dir.setObjectName("pushButton_open_material_sp_dir")
        self.gridLayout.addWidget(self.pushButton_open_material_sp_dir, 3, 3, 1, 1)
        self.lineEdit_path_dir_material_sp = Button(self.centralwidget)
        self.lineEdit_path_dir_material_sp.setObjectName("lineEdit_path_dir_material_sp")
        self.gridLayout.addWidget(self.lineEdit_path_dir_material_sp, 3, 1, 1, 2)
        self.pushButton_open_unloading_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_unloading_file.setObjectName("pushButton_open_unloading_file")
        self.gridLayout.addWidget(self.pushButton_open_unloading_file, 4, 3, 1, 1)
        self.pushButton_open_load_asu_dir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_load_asu_dir.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open_load_asu_dir.sizePolicy().hasHeightForWidth())
        self.pushButton_open_load_asu_dir.setSizePolicy(sizePolicy)
        self.pushButton_open_load_asu_dir.setObjectName("pushButton_open_load_asu_dir")
        self.gridLayout.addWidget(self.pushButton_open_load_asu_dir, 6, 3, 1, 1)
        self.lineEdit_path_dir_finish = Button(self.centralwidget)
        self.lineEdit_path_dir_finish.setObjectName("lineEdit_path_dir_finish")
        self.gridLayout.addWidget(self.lineEdit_path_dir_finish, 8, 1, 1, 2)
        self.lineEdit_path_dir_load_asu = Button(self.centralwidget)
        self.lineEdit_path_dir_load_asu.setEnabled(False)
        self.lineEdit_path_dir_load_asu.setObjectName("lineEdit_path_dir_load_asu")
        self.gridLayout.addWidget(self.lineEdit_path_dir_load_asu, 6, 1, 1, 2)
        self.lineEdit_name_set = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name_set.setEnabled(False)
        self.lineEdit_name_set.setObjectName("lineEdit_name_set")
        self.gridLayout.addWidget(self.lineEdit_name_set, 10, 1, 1, 3)
        self.label_unformat_file = QtWidgets.QLabel(self.centralwidget)
        self.label_unformat_file.setObjectName("label_unformat_file")
        self.gridLayout.addWidget(self.label_unformat_file, 0, 0, 1, 1)
        self.lineEdit_path_file_unloading = Button(self.centralwidget)
        self.lineEdit_path_file_unloading.setObjectName("lineEdit_path_file_unloading")
        self.gridLayout.addWidget(self.lineEdit_path_file_unloading, 4, 1, 1, 2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 4)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.action_default_window = QtWidgets.QAction(mainWindow)
        self.action_default_window.setObjectName("action_default_window")
        self.menu.addAction(self.action_default_window)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(mainWindow)
        self.checkBox_name_gk.toggled['bool'].connect(self.lineEdit_name_gk.setEnabled) # type: ignore
        self.checkBox_name_set.toggled['bool'].connect(self.lineEdit_name_set.setEnabled) # type: ignore
        self.radioButton_load_asu.toggled['bool'].connect(self.lineEdit_path_dir_load_asu.setEnabled) # type: ignore
        self.radioButton_load_manufacture.toggled['bool'].connect(self.lineEdit_path_file_manufacture.setEnabled) # type: ignore
        self.radioButton_load_asu.toggled['bool'].connect(self.pushButton_open_load_asu_dir.setEnabled) # type: ignore
        self.radioButton_load_manufacture.toggled['bool'].connect(self.pushButton_open_load_manufacture_file.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Главное окно"))
        self.label_finish_folder.setText(_translate("mainWindow", "Конечная папка"))
        self.pushButton_start.setText(_translate("mainWindow", "Старт"))
        self.pushButton_open_path_finish_dir.setText(_translate("mainWindow", "Открыть"))
        self.pushButton_open_unformat_file.setText(_translate("mainWindow", "Открыть"))
        self.checkBox_name_gk.setText(_translate("mainWindow", "Наименование ГК"))
        self.pushButton_open_load_manufacture_file.setText(_translate("mainWindow", "Открыть"))
        self.radioButton_load_manufacture.setText(_translate("mainWindow", "Файл выгрузки"))
        self.label_unloading_file.setText(_translate("mainWindow", "Файл производства"))
        self.radioButton_load_asu.setText(_translate("mainWindow", "Папка с выгрузками АСУ"))
        self.label_material_sp.setText(_translate("mainWindow", "Папка с материалами"))
        self.checkBox_name_set.setText(_translate("mainWindow", "Наименование к-та"))
        self.pushButton_form_file.setText(_translate("mainWindow", "Сформировать выгрузку из файла"))
        self.pushButton_open_material_sp_dir.setText(_translate("mainWindow", "Открыть"))
        self.pushButton_open_unloading_file.setText(_translate("mainWindow", "Открыть"))
        self.pushButton_open_load_asu_dir.setText(_translate("mainWindow", "Открыть"))
        self.label_unformat_file.setText(_translate("mainWindow", "Неподготовленный файл"))
        self.menu.setTitle(_translate("mainWindow", "Настройки"))
        self.action_default_window.setText(_translate("mainWindow", "Настройки по умолчанию"))
